### ISSUE TITLE
Conversion Fails With mGBA Save Files With RTC Data Appended

### ISSUE THREAD

**Issue by jackada7** [Thysbelon/gbaconv-web#9] opened 2024-03-02 23:20 UTC
So I was transferring save files from 44VBA on my iphone to mGBA on my mac. It all worked perfectly first, but after I saved again in mGBA and tried to convert that new .sav file back to .4gs, 44VBA opened that file and told me that "The save file has been deleted". I even tried to convert that new .4gs file back to .sav, and now even mGBA is telling me that "The save file has been deleted". 
I have tested with several other save files, and it turns out that they all worked fine after several conversions, but if I just take a save file and save once on mGBA, the conversion just won't work. 

I know this sounds a lot like a mGBA issue, but this is just so weird so I just wanna know if you can do anything with this. 

Debug output if needed: 
home/web_user/savedata.sav
0
0
255
255
177
99
255
252
159
191
filename: /home/web_user/savedata.sav
len: 131088
Detected save type: Unknown type
Cannot infer save type ...
Assuming a save type of SRAM.
filename: home/web_user/savedata.srm

**Comment by Thysbelon** [comment] 2024-03-03 17:05
Thank you for reporting this. I was able to recreate this issue instantly using Pokémon Emerald.
After some research, I discovered that the cause of this is the fact that [mGBA appends RTC data to the save files of games that use an RTC](https://github.com/mgba-emu/mgba/issues/2718). 
I'll try to fix the webapp to handle these save files properly when I have the time.

**Comment by Thysbelon** [comment] 2024-03-03 20:06
This should be fixed by [commit 1409be2](https://github.com/Thysbelon/gbaconv-web/commit/1409be23d0d322146da518e758ccc12700fe52ed)

**Closed as completed by Thysbelon** 2024-03-03 20:06 UTC
Labels: bug

**Comment by jackada7** [comment] 2024-03-03 22:09
Thank you so much for your help!

**Comment by Thysbelon** [comment] 2024-03-04 00:37
You're welcome! 😊
